### ISSUE TITLE
error about GetStart

### ISSUE THREAD

**Issue by miss-rain** [ZhengyiLuo/MEVA#1]
hi great project!

When I run GetStart command,
the error called:
    ImportError: cannot import name 'ModelOutput' from 'smplx.body_models'
and 
   No matching distribution found for multi_person_tracker

**Comment by ZhengyiLuo** [comment]
Updated the description & install instructions; would you mind trying those? 8375445d418f1c316135f63df3209476d3c83a7c

**Comment by miss-rain** [comment]
hi thanks
i try again but have another error:
         **ImportError: cannot import name 'ModelOutput' from 'smplx.body_models'**          (/opt/anaconda3/envs/jupyter/lib/python3.8/site-packages/smplx/body_models.py)

**Comment by tetsu** [comment]
I encountered the same issue. The latest 'smplx.body_models' doesn't seem to have 'ModelOutput'. Maybe we should specify smplx version, or use different library?

**Comment by ZhengyiLuo** [comment]
@tetsu @miss-rain 

Indeed, I changed my local installation of the smplx repo so I didn't have this issue. I have pushed my change to a local fork and revised the requirements.txt file; now it should work. Would you mind trying it out? 

24af9ee26a639b355ac7cb01c3da16bbad3033a4

**Comment by ZhengyiLuo** [comment]
Close since it seems resolved.

**Comment by FatherPrime** [comment]
> @tetsu @miss-rain
> 
> Indeed, I changed my local installation of the smplx repo so I didn't have this issue. I have pushed my change to a local fork and revised the requirements.txt file; now it should work. Would you mind trying it out?
> 
> Specifically, instead of install smplx from pip, use `pip install git+https://github.com/ZhengyiLuo/smplx.git`
> 
> [24af9ee](https://github.com/ZhengyiLuo/MEVA/commit/24af9ee26a639b355ac7cb01c3da16bbad3033a4)

After pip install git+https://github.com/ZhengyiLuo/smplx.git  ，the problem is still existing. Can you help me ?


`Traceback (most recent call last):
  File "scripts/run_meva_on_video.py", line 23, in <module>
    from meva.lib.meva_model import MEVA, MEVA_demo
  File "/home/video3d/MEVA-master/meva/lib/meva_model.py", line 14, in <module>
    from meva.lib.spin import Regressor, hmr
  File "/home/video3d/MEVA-master/meva/lib/spin.py", line 13, in <module>
    from meva.lib.smpl import SMPL, SMPL_MODEL_DIR, H36M_TO_J14, SMPL_MEAN_PARAMS
  File "/home/video3d/MEVA-master/meva/lib/smpl.py", line 8, in <module>
    from smplx.body_models import ModelOutput
ImportError: cannot import name 'ModelOutput' from 'smplx.body_models' (/home/video3d/anaconda3/envs/meva/lib/python3.7/site-packages/smplx/body_models.py)`

**Comment by FatherPrime** [comment]
> @tetsu @miss-rain
> 
> Indeed, I changed my local installation of the smplx repo so I didn't have this issue. I have pushed my change to a local fork and revised the requirements.txt file; now it should work. Would you mind trying it out?
> 
> Specifically, instead of install smplx from pip, use `pip install git+https://github.com/ZhengyiLuo/smplx.git`
> 
> [24af9ee](https://github.com/ZhengyiLuo/MEVA/commit/24af9ee26a639b355ac7cb01c3da16bbad3033a4)

After pip install git+https://github.com/ZhengyiLuo/smplx.git  ，the problem is still existing. Can you help me ?


`Traceback (most recent call last):
  File "scripts/run_meva_on_video.py", line 23, in <module>
    from meva.lib.meva_model import MEVA, MEVA_demo
  File "/home/video3d/MEVA-master/meva/lib/meva_model.py", line 14, in <module>
    from meva.lib.spin import Regressor, hmr
  File "/home/video3d/MEVA-master/meva/lib/spin.py", line 13, in <module>
    from meva.lib.smpl import SMPL, SMPL_MODEL_DIR, H36M_TO_J14, SMPL_MEAN_PARAMS
  File "/home/video3d/MEVA-master/meva/lib/smpl.py", line 8, in <module>
    from smplx.body_models import ModelOutput
ImportError: cannot import name 'ModelOutput' from 'smplx.body_models' (/home/video3d/anaconda3/envs/meva/lib/python3.7/site-packages/smplx/body_models.py)`
